DROP TABLE IF EXISTS user;
CREATE TABLE user
(
    id                 INTEGER PRIMARY KEY AUTO_INCREMENT,
    username           VARCHAR(32) NOT NULL UNIQUE,
    encrypted_password CHAR(32)    NOT NULL,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted            BOOLEAN     NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS article;
CREATE TABLE article
(
    id         INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id    INTEGER      NOT NULL,
    title      VARCHAR(256) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE
)